---
title: "How to Use The Covid19cvdata datasets"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
## Installation

You can install the released version of covid19italy from [Github](https://github.com/marovski/covid19cvdata) with:

``` {r}
devtools::install_github("marovski/covid19cvdata")

```
### Load the library
```{r }
library(covid19cvdata)

data.update()
```

### Load the your dataset covid19cv
```{r}
dataset<-covid19cvdata::covid19cv
```
### Load the your dataset covid19cv_nacional (Containing totals by case type)
```{r}
dataset<-covid19cvdata::covid19cv_nacional
```
### Load the your dataset covid19cv_concelhos (Containing totals by cities)
```{r}
dataset<-covid19cvdata::covid19cv_concelhos
```
### Load the your dataset covid19cv_pop (Containing totals by demographics)
```{r}
dataset<-covid19cvdata::covid19cv_pop
```
